[env:waveshare_esp32s3_touch_43b]
platform = espressif32@53.3.12
; If your PlatformIO is older and doesn't see this board, run:
; pio platform update espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino


; Keep your custom variant if you want WS_* macros available
board_build.variants_dir = variants
board_build.variant = waveshare_43b

; 16MB flash, PSRAM on
board_build.partitions = default_16MB.csv
board_build.psram = enabled

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DLV_CONF_INCLUDE_SIMPLE
  -DLV_CONF_PATH="lv_conf.h"
  -DESP_PANEL_BOARD_DEFAULT_USE_CUSTOM=1
  -std=gnu++17
  -I include

build_unflags = -std=gnu++11
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time

upload_protocol = esptool
upload_speed = 921600
; upload_port = <your-port>  ; set this if auto-detect fails

lib_deps =
  bblanchon/ArduinoJson @ ^6.21.5
;   espressif/ESP32_Display_Panel
;   espressif/ESP32_IO_Expander
;   espressif/ESP32_Arduino_Utils
;   lvgl/lvgl @ ^8.3.11
;   lvgl/lv_demos @ ^8.3.11
